# Generated by Django 5.2.17 on 2026-08-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='agent_reply',
            field=models.TextField(blank=True),
        ),
    ]
